const express = require('express')
const routes = express.Router()
const react = require('../controllers/react.controller')
const link = require('../controllers/link.controllers')
const skill = require('../controllers/skills.controllers')
const project = require('../controllers/project.controllers')
const contact = require('../controllers/contact.controller')
routes.route('/skills')
    .post(skill.InsertSkills)
    .get(skill.ViewSkills)
routes.route('/link')
    .post(link.InsertLink)
    .get(link.ViewLink)
routes.route('/project')
    .post(project.InsertProject)
    .get(project.ViewProject)
routes.route('/project/:id')
    .get(project.SingleViewProject)
routes.route('/contact')
    .post(contact.InsertContact)
    .get(contact.ViewContact)
    routes.route('/*').get(react.reactPage)
module.exports = routes